# action.yml
name: 'Alerts'
description: 'Application Insights Alerts'
inputs:
  app-id:  # id of input
    description: 'The Application ID'
    required: true
  api-key:
    description: 'The API key'
    required: true
  query:
    description: 'The Analytics query'
    required: true
  timespan:
    description: 'The timespan over which to query data'
    required: false
    default: PT1H
outputs:
  timestamp:
    description: 'Time'
  exceptionType:
    description: 'Type'
  method:
    description: 'Method'
  message:
    description: 'Message'
  assembly:
    description: 'Assembly'
  count:
    description: 'Exception count'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app-id }}
    - ${{ inputs.api-key }}
    - ${{ inputs.query }}
    - ${{ inputs.timespan }}