# action.yml
name: 'Alerts'
description: 'Application Insights Alerts'
inputs:
  app-id:  # id of input
    description: 'The Application ID'
    required: true
  api-key:
    description: 'The API key'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.app-id }}
    - ${{ inputs.api-key }}