on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Application Insights
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          api-key: ${{ secrets.API_KEY }}
          query: "exceptions | take 1"
          timespan: "PT1H" #default PT1H
      # Use the output from the `hello` step
      - name: Notify
        uses: k0kubun/action-slack@v1.0.0
        with:
          payload: |
            {
              "text": ":boom: Since last run we have detected ${{ steps.hello.outputs.count }} new exceptions",
              "attachments": [{
                "title": "Last error",
                "fields": [
                {
                  "title": "Exception Type",
                  "value": "${{ steps.hello.outputs.exceptionType }}",
                  "short": true
                },
                {
                  "title": "Method",
                  "value": "${{ steps.hello.outputs.method }}",
                  "short": true
                },
                {
                  "title": "Message",
                  "value": "${{ steps.hello.outputs.message }}",
                  "short": false
                },
                {
                  "title": "Assembly",
                  "value": "${{ steps.hello.outputs.assembly }}",
                  "short": false
                }],
                "footer": "${{ steps.hello.outputs.timestamp }}",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      # - name: Get the output time
      #   run: echo "The timestamp was ${{ steps.hello.outputs.timestamp }}"