on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ai_job:
    runs-on: ubuntu-latest
    name: Application Insights exception retriever
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Retrieve Application Insight exceptions
        uses: ./ # Uses an action in the root directory
        id: ai
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          api-key: ${{ secrets.API_KEY }}
          query: "exceptions | where outerType startswith 'System.' | where outerMessage !contains '.txt' | where outerMessage !contains 'was not found or does not implement IController.'"
          timespan: "PT1H" #default PT1H
      - name: Notify
        if: success()
        uses: k0kubun/action-slack@v1.0.0
        with:
          payload: |
            {
              "text": ":boom: Since last run we have detected ${{ steps.ai.outputs.count }} new exceptions",
              "attachments": [{
                "title": "Last error",
                "fields": [
                {
                  "title": "Exception Type",
                  "value": "${{ steps.ai.outputs.exceptionType }}",
                  "short": true
                },
                {
                  "title": "Method",
                  "value": "${{ steps.ai.outputs.method }}",
                  "short": true
                },
                {
                  "title": "Message",
                  "value": "${{ steps.ai.outputs.message }}",
                  "short": false
                },
                {
                  "title": "Assembly",
                  "value": "${{ steps.ai.outputs.assembly }}",
                  "short": false
                }],
                "footer": "${{ steps.ai.outputs.timestamp }}",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}