on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          app-id: ${{ secrets.APPLICATION_ID }}
          api-key: ${{ secrets.API_KEY }}
          query: "exceptions | take 1"
          timespan: "PT1H" #default PT1H
      # Use the output from the `hello` step
      - name: Notify
        uses: k0kubun/action-slack@v1.0.0
        with:
          payload: |
            {
              "attachments": [{
                "title": "A new exception has been detected in dev app",
                "title_link": "title link",
                "text": "text",
                "fields": [{ "value": "field", "short": false }],
                "footer": "footer",
                "color": "danger"
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      # - name: Get the output time
      #   run: echo "The timestamp was ${{ steps.hello.outputs.timestamp }}"