on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          app-id: 'the app id'
          api-key: 'the api key'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
      - name: Slack Notify
        uses: rtCamp/action-slack-notify@v2.0.1
        env:
          SLACK_CHANNEL: foo
          SLACK_COLOR: '#3278BD'
          SLACK_ICON: https://connectoricons-prod.azureedge.net/applicationinsights/icon_1.0.1316.1923.png
          SLACK_MESSAGE: "The time was ${{ steps.hello.outputs.time }}"
          SLACK_TITLE: "A new exception has been detected in ..."
          SLACK_USERNAME: 'Application Insights'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

